import Head from "next/head.js"

import Homepage from "../components/Homepage.jsx"
import { useContext } from "react"
// import Checkout from "./Checkout.js"
import {solarzuContext} from '../components/layout';



export default function Home() { 
  const { setHome } = useContext(solarzuContext);
  setHome(true);
  return (
    <div>
      <Head>
        <title>Solarzu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
       <Homepage /> 
     
    </div>
  )
}




// "@truffle/hdwallet-provider": "^2.0.10-alpha.2",
 // "wyvern-schemas": "^0.6.15"